version: '3.4'

services:
  schoolapi:
    build:
      context: .
      dockerfile: src/SchoolAPI/Dockerfile
    ports:
      - 5206:5206
    networks:
      - gateway_network
    volumes:
      - ./logs:/app/logs
    environment:
      DB_HOST: mysql-master-school
      MySQLDB_USER: root
      DB_PASSWORD: admin#123
      DB_NAME: school
    depends_on:
      - mysql-master-school
    

  userapi:
    build:
      context: .
      dockerfile: src/UserAPI/Dockerfile
    ports:
      - 5050:5050
    networks:
      - gateway_network
    volumes:
      - ./logs:/app/logs
    environment:
      DB_HOST: mysql-master-school
      MySQLDB_USER: root
      DB_PASSWORD: admin#123
      DB_NAME: schooluserdb
    depends_on:
      - mysql-master-school

  apigateway:
    build:
      context: .
      dockerfile: src/API.Gateway/Dockerfile
    ports:
      - 5044:5044
    networks:
      - gateway_network
    depends_on:
      - schoolapi
      - userapi
    volumes:
      - ./logs:/app/logs

  mysql-master-school:
    image: mysql:8.0
    restart: always
    volumes:
      - datafiles:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin#123
    ports:
      - 3305:3306
    networks:
      - gateway_network


networks:
  gateway_network:
    driver: bridge

volumes:
  datafiles:

